In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
fl=pd.read_csv("keralafloods.csv")

In [2]:
fl.head()

Cities  year     may    june    july  temperature  altitude         avg  \
0  ALAPPUZHA  2001  298.70  177.90  177.90           24       390  218.166667   
1  ALAPPUZHA  2003  118.60  118.60   59.30           21       390   98.833333   
2  ALAPPUZHA  2000   89.61   89.61   59.74           23       390   79.653333   
3      ANGUL  2001   55.40   61.74   61.74           21       276   59.626667   
4      ANGUL  2003   41.16   41.16   20.58           25       276   34.300000   

   label  
0      1  
1      0  
2      0  
3      0  
4      0

In [3]:
fl.fillna(0)

Cities  year     may    june    july  temperature  altitude  \
0    ALAPPUZHA  2001  298.70  177.90  177.90           24       390   
1    ALAPPUZHA  2003  118.60  118.60   59.30           21       390   
2    ALAPPUZHA  2000   89.61   89.61   59.74           23       390   
3        ANGUL  2001   55.40   61.74   61.74           21       276   
4        ANGUL  2003   41.16   41.16   20.58           25       276   
..         ...   ...     ...     ...     ...          ...       ...   
127   THRISSUR  2003  141.48  141.48   70.74           26       341   
128   THRISSUR  2000   86.73   86.73   57.82           25       341   
129    WAYANAD  2003  698.10  333.12  333.12           27       214   
130    WAYANAD  2001  139.62  139.62   69.81           29       214   
131    WAYANAD  2000   52.38   52.38   34.92           27       214   

            avg  label  
0    218.166667      1  
1     98.833333      0  
2     79.653333      0  
3     59.626667      0  
4     34.300000      0  
..          ...    ...  
127  117.900000      0  
128   77.093333      0  
129  454.780000      1  
130  116.350000      0  
131   46.560000      0  

[132 rows x 9 columns]

In [20]:
x=fl.iloc[:,5:8].values
y=fl.iloc[:,-1].values

In [21]:
print(x)
#print(y)

[[ 24.         390.         218.1666667 ]
 [ 21.         390.          98.83333333]
 [ 23.         390.          79.65333333]
 [ 21.         276.          59.62666667]
 [ 25.         276.          34.3       ]
 [ 27.         276.          14.77333333]
 [ 30.         378.          92.12      ]
 [ 24.         378.          43.18333333]
 [ 24.         378.          32.24      ]
 [ 25.         211.          44.18      ]
 [ 23.         211.          31.4       ]
 [ 24.         211.           5.2       ]
 [ 24.         301.          78.31333333]
 [ 26.         301.          36.4       ]
 [ 24.         301.          27.70666667]
 [ 28.         377.          52.6       ]
 [ 24.         377.          33.41666667]
 [ 24.         377.          10.        ]
 [ 25.         369.          62.67333333]
 [ 26.         369.          33.28333333]
 [ 28.         369.          18.18666667]
 [ 27.         185.         248.8133333 ]
 [ 26.         185.         142.0666667 ]
 [ 23.         185.          62.66

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [23]:
from sklearn.linear_model import LinearRegression
regg=LinearRegression()
regg.fit(x_train,y_train)

LinearRegression()

In [24]:
print(regg.intercept_)

-0.15558143966922933


In [25]:
print(regg.coef_)

[3.40025845e-04 7.27679142e-06 3.98877304e-03]


In [26]:
print("Mean squared error: %.2f" % np.mean((regg.predict(x_test) - y_test) ** 2))
print('Variance score: %.2f' % regg.score(x_test, y_test))
r2_score = regg.score(x_test,y_test)
print(r2_score)

Mean squared error: 0.03
Variance score: 0.72
0.7169689889531263


In [27]:
para=[[21,390,98.833333]]

In [28]:
predfl=regg.predict(para)
print(predfl)

[0.24862079]


In [29]:
if(predfl >0):
    print("floods")
else:
    print("no floods")

floods
